### ISSUE TITLE
关于Classifier里的batchnorm

### ISSUE THREAD

**Issue by kpmokpmo** [NeuralCollapseApplications/ImbalancedLearning#1]
作者您好，

现在很多大型网络后面只有一个fc层，比如post-norm的transformer后面的classifier部分完全可以不加norm。论文中没有提及etf classifier里的batchnorm，这个让我联想到Logit Attenuating Weight Normalization（虽然这篇是calibration，但某种程度上姑且也是缓解imbalance问题）和其他几篇对logit做正则的文章，不知这个是可有可无的还是比较重要的？谢谢。

**Comment by iboing** [comment]
您好，感谢关注。Neural collapse中描述的现象是针对去中心化后的特征(h-\bar{h})，所以我们对最后特征加了BN层。实验上，一些情况下会有更好的效果，一些情况下可有可无。
