### ISSUE TITLE
可以提供CUB数据集的训练设置文件和数据处理代码吗？

### ISSUE THREAD

**Issue by mobulan** [NeuralCollapseApplications/ImbalancedLearning#2]
非常感谢你的工作，提供了十分新奇的思路。cifar数据集也可以复现精度。但是在CUB数据集上，我按照文中附录的设置，模型无法收敛，不知道是哪里设置的问题。请问可以提供CUB数据集的训练设置yaml文件，以及数据集加载以及预处理相关代码吗，非常感谢。

**Comment by iboing** [comment]
CUB 和其他数据集不一样，需要预训练，可能是这个原因。在incremental learning任务上有CUB的数据集部分的代码，可以参考下，https://github.com/NeuralCollapseApplications/FSCIL
