### ISSUE TITLE
Implementation of dot regression loss is inconsistent with the equation in the paper.

### ISSUE THREAD

**Issue by zhb2000** [NeuralCollapseApplications/ImbalancedLearning#3]
In the paper, dot regression loss is defined as 

$$
\mathcal{L}_{DR}(\mathbf{h}, \mathbf{W}^*) = \frac{1}{2\sqrt{E_W E_H}}\left(\mathbf{w}^{*T}_c\mathbf{h} - \sqrt{E_W E_H}\right)^2.
$$

However, the implementation in the code is

https://github.com/NeuralCollapseApplications/ImbalancedLearning/blob/2ebb309dddcd0ac8b18222fd06357099260bc169/methods.py#L18-L23

which losses the $\sqrt{E_W}$  term in the denominator.

**Comment by iboing** [comment]
\sqrt(E_W) is 1 by default. Thank you for your attention.

**Comment by tom4649** [comment]
Appendix C of your paper indicates that the default setting of 1 corresponds to $\(\sqrt{E_H}\)$, not $\(\sqrt{E_W}\)$. Your implementation corroborates [your code](https://github.com/NeuralCollapseApplications/ImbalancedLearning/blob/main/models/densenet.py#L175). However, $\(\sqrt{E_W}\)$ is not set to 1 in either your implementation or the appendix's description. Therefore, it appears necessary to include $\(\sqrt{E_W}\)$ in the denominator.

**Comment by iboing** [comment]
Thanks for your careful feedback. \sqrt{E_W} is also fixed as 1, see [this line](https://github.com/NeuralCollapseApplications/ImbalancedLearning/blob/main/models/densenet.py#L149)
